### ISSUE TITLE
Memory Failure with higher resolution or frame numbers

### ISSUE THREAD

**Issue by MHamedM** [jphdotam/keras_generator_example#1]
Hi,
Thanks for the code and example. Just wondering if you tried it with more frames?
I tried it on UCF101 (32,80,80,3) with batch size of 16 and it worked fine but it failes with resolutions higher than 80*80. I noticed you had 299*299 but on 10 frames and wondering if you ever experienced any memory issue with higher number of frames (more than 10) or higher resolutions (more than 299*299)

**Comment by vinitmuchhala** [comment]
@MHamedM are you using the same GPU as the author? If not, it might depend on the GPU memory available to you. 
Based on the error you are getting it might also depend on the model you are feeding the generator into.
You might try reducing the batch size. It has worked fairly well for most of the OOM issues
