### ISSUE TITLE
Invalid Syntax ?

### ISSUE THREAD

**Issue by akbacak** [jphdotam/keras_generator_example#2]
File "/home/ubuntu/keras/enver/acrec/VideoGenerator.py", line 30
    filenames = glob.glob(os.path.join(dir, f"**/*{self.file_ext}"))
                                                                 ^
SyntaxError: invalid syntax

**Comment by jphdotam** [comment]
Hi, what version of Python are you using? f strings were introduced in python 3.6 so it might be you have a version before that...

**Comment by akbacak** [comment]
Im using Python 2.7.15rc1.
 I removed **f** from **filenames = glob.glob(os.path.join(dir, f"**/*{self.file_ext}"))** in the 30th line of VideoGenerator.py

Now the only error is 
self.training_generator = self.generator.generate(train_or_test='train')
NameError: name 'self' is not defined

My code: 

import ....
..............
from VideoGenerator import *

model = ....
model.compile(.....)

generator = VideoGenerator(train_dir="/home/ubuntu/keras/enver/acrec/data/train/",
                                test_dir="/home/ubuntu/keras/enver/acrec/data/test/",
                                dims=(10, 224, 224, 3),
                                batch_size=1,
                                shuffle=True,
                                file_ext=".np*")

self.training_generator = self.generator.generate(train_or_test='train')
self.training_steps_per_epoch = len(self.generator.filenames_train) // self.batch_size
self.testing_generator = self.generator.generate(train_or_test="test")
self.testing_steps_per_epoch = len(self.generator.filenames_test) // self.batch_size

self.model.fit_generator(self.training_generator,
                         steps_per_epoch=self.training_steps_per_epoch,
                         epochs=epochs,
                         validation_data=self.testing_generator,
                         validation_steps=self.testing_steps_per_epoch)


is that ok ?

**Comment by jphdotam** [comment]
Hi I think maybe you need to do a little more reading about python strings and object oriented programming in python. However, to get your code to work:

1) If you remove the f it wont work because the file extension wont be inserted into the string. You need to do something like glob.glob(os.path.join(dir, "/*"+self.file_ext))

2) The self is just if you instantiate the generator inside a class, which you're not doing. If you remove all the 'selfs' it should work.

**Comment by akbacak** [comment]
I know this man, I read already read something.
Your code seems working for me, but I think your generator only works for sequential models? 
My model is Keras functional API, I got this error:

 File "vacrec_v4.py", line 73, in <module>
    validation_steps=testing_steps_per_epoch)
  File "/home/ubuntu/tensorflow/venv/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/tensorflow/venv/local/lib/python2.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/tensorflow/venv/local/lib/python2.7/site-packages/keras/engine/training_generator.py", line 68, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.

**Comment by akbacak** [comment]
Code is working by python3 for me now, by high memory. I closed topics, Thank you...
